version: "3.1"
services:
  mysql:
    image: mysql
    container_name: mysql
    command: [ "mysqld", "--mysql-native-password=ON" ]
    volumes:
      - mysql-data:/var/local/mysql/data
    ports:
      - "3306:3306"
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mysql

volumes:
  mysql-data:
    driver: local